### ISSUE TITLE
no bitwise support found

### ISSUE THREAD

**Issue by striveQiao** [somesocks/lua-lockbox#37]
when i run lua RunTest.lua 
![image](https://user-images.githubusercontent.com/49113945/162394901-1b738e5d-f658-4066-84d6-8d831bb0dc85.png)
how to fix it

**Comment by tst2005** [comment]
- [ ] lua 5.1 does NOT have builtin bitwise support.
- [x] lua 5.2 have a builtin module named "bit32"
- [x] lua 5.3 have native operators (and usually still the "bit32" builtin module, for compat)
- [x] lua 5.4 have bitwise support (probably like lua 5.3)
- [x] luajit 2.0 and 2.1 have builtin module named "bit"

You just have to find another Lua version because you probably use the only one that have no bitwise support at all.

Enjoy!

**Comment by somesocks** [comment]
Closing this issue, as @tst2005 said this is a Lua version problem, not a library issue

**Comment by mecampbellsoup** [comment]
doesn't seem to work w/ lua 5.4 either:

```
[api-gateway] /usr/local/share/lua/5.4/lockbox/util/bit.lua:12: no bitwise support found
```
